### PR TITLE
resolve 'Select' from defaultRenderers

### PR DESCRIPTION
**Pull request by develomark**
Small change to allow for enums to be included in defaultRenderers like scalar types:

`Select: props => {
...
}`

### CODE REVIEW

**Comment by mstn** [comment]
Hi @develomark, thanks for your PR! 

I am not sure to have understood what your PR does.

If you want to define a custom render for an enum type, you can override the type name as we do for 'Currency' [here](https://github.com/Fundflow/apollo-redux-form/blob/master/stories/MonetaryAmount.js#L50). Does it make sense?

**Comment by develomark** [comment]
Hi Marco,

Thanks for your response. Your example makes sense when there are a small number of enums. In the case there are lots that all require the same component; not so much. 

The power of the library you have created here is that you do not have to be aware of the schema - this can change, or be dynamically created at runtime depending upon the user and context. This is hugely powerful! 

For all the scalar types we can override the defaults (your defaultRenderers.js example), but with enums and arrays currently we cannot configure our own default component/render function and are left with:

```
const defaultRenderSelectField = (props: FieldProps) => {
  const { input, label, options, meta: { touched, error, warning }, ...rest } = props;
  return (
    <div>
      <label>{label}</label>
      <div>
        <select {...input} {...rest} >
          {options.map( ({key, value}: {key: string; value: string}) =>
              <option key={key} value={value}>{value}</option> )}
        </select>
        {touched && ((error && <span>{error}</span>) || (warning && <span>{warning}</span>))}
      </div>
    </div>
  );
};
```

The pull request allows a user to configure a render function for all `Enums` and override the default with their own. In my own case I have a component that renders out buttons for 2-4 items, radio buttons for 5-8 items and a Select dropdown for >8 items, if there are more than 15 items then search is enabled.

The benefit is that this keeps things DRY, rather than copy pasting the same render function multiple times for each enum in more complex schemas. 

I would like to propose that we do something similar for Arrays and FormSections also...

Best regards,
Mark

**Comment by develomark** [comment]
@mstn does this make sense? Are there any changes you'd like me to make?

**Comment by mstn** [comment]
Hi @develomark,

Thanks for the explanation. 

It makes sense. You want to define a custom render for all enums independently from their names. As you observe, the same reasoning holds for sections and arrays. Unfortunately, at the moment, you can override the behavior only for specific types or field names. Is it correct?

I would add another set of renderers for GraphQL type constructors such as enums, sections and arrays. The reason is that renderers property is for types (ok, the name was not a good choice!) and generic enums are not types but more a kind of type constructors.

So, we could have three sets of renderers
* by field name
* by type
* by type constructor
* defaults (maybe we should deprecate this one since nobody is happy with the original defaults)

We choose the actual render in that order. For example, if we define a render by field name, it should have priority over any render by type.

Does it make sense?

**Comment by develomark** [comment]
@mstn 

Yes that makes sense.

To align with Graphql language (http://graphql.org/learn/schema/):
- by field
- by object type
- (user defined defaults) - by scalar types, enum, array, section
- built-in defaults

Defaults I think you should keep; yes everyone will probably override them, but it does allow people to quickly get up and running without fully understanding how it works in the first instance.

**Comment by mstn** [comment]
@develomark I would not update apollo, redux-form or any other dep in this PR if it is not strictly necessary. Moreover, apollo should remain a devDependency.

**Comment by develomark** [comment]
I shall close this.

**Comment by mstn** [comment]
Hey Mark, your pr was a good idea. Do you need help?

**Pull request closed without merging**
